name: Continuous Integration Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: ['Debug','Coverage']
        c_compiler: [gcc, clang]
        mpiType: ['openMPI', 'none']
        fortran_compatible: [on, off]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

          - mpiType: 'openMPI'
            use_mpi: on
            oversubscribe: on
          - mpiType: 'none'
            use_mpi: off
            oversubscribe: off

          - os: macos-latest
            c_compiler: gcc-14
            cpp_compiler: gcc-14
            fortran_compiler: gfortran-14
            mpiType: 'none'
            build_type: Debug

        exclude:
          # Coverage only works with gcc
          - build_type: 'Coverage'
            c_compiler: clang

    steps:
    - uses: actions/checkout@v4

    - if: matrix.mpiType == 'openMPI'
      name: Install OpenMPI
      run: sudo apt-get update && sudo apt-get install -y openmpi-bin libopenmpi-dev && mpirun --version

    - if: matrix.build_type == 'Coverage'
      name: Install lcov
      run: sudo apt-get update && sudo apt install -y lcov

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_Fortran_COMPILER=${{ matrix.fortran_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_COMPILE_WARNING_AS_ERROR=on
        -DELA_USE_MPI=${{ matrix.use_mpi }}
        -DFORTRAN_COMPATIBLE=${{ matrix.fortran_compatible }}
        -DBUILD_TESTING=on
        -DMPIRUN_OVERSUBSCRIBE=${{ matrix.oversubscribe }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - if: matrix.build_type == 'Coverage'
      name: Baseline coverage report
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        lcov --directory . --capture --initial --output-file ./coverage_base.info --ignore-errors mismatch

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }} --rerun-failed --output-on-failure

    - if: matrix.build_type == 'Coverage'
      name: Create coverage report
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        lcov --directory . --capture --output-file ./coverage_test.info --ignore-errors mismatch
        lcov -a ./coverage_test.info -a ./coverage_base.info --output-file ./coverage.info

    - if: matrix.build_type == 'Coverage'
      name: Upload coverage report
      uses: codecov/codecov-action@v4.5.0
      with:
        file: ${{ steps.strings.outputs.build-output-dir }}/coverage.info
        fail_ci_if_error: true
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
